#!/usr/bin/env bash
# Bring up the fully-local Supabase dev stack (Colima + Supabase CLI).
# Idempotent: safe to run repeatedly.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1) Container runtime — start Colima if it isn't already up.
if ! colima status >/dev/null 2>&1; then
  echo "▶ Starting Colima (2 CPU / 4 GB)…"
  colima start --cpu 2 --memory 4 --disk 20
else
  echo "✔ Colima already running"
fi
# Point the Docker client (and Supabase CLI) at Colima's socket.
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"

# 2) Supabase stack (applies migrations + seed on first start).
echo "▶ Starting Supabase…"
supabase start

# 3) Sync the web app's dev env with the local credentials.
env_out="$(supabase status -o env)"
api_url="$(printf '%s\n' "$env_out" | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
anon_key="$(printf '%s\n' "$env_out" | sed -n 's/^ANON_KEY="\(.*\)"$/\1/p')"
cat > apps/web/.env.development <<EOF
# Auto-generated by scripts/dev-up.sh — points the web app at local Supabase.
VITE_SUPABASE_URL=${api_url}
VITE_SUPABASE_PUBLISHABLE_KEY=${anon_key}
EOF
echo "✔ Wrote apps/web/.env.development (API: ${api_url})"

echo
echo "Local Supabase is up. Next: pnpm dev:web  →  http://localhost:33718"
echo "Studio: run 'supabase status' to see the Studio URL."
