-- ============================================================================
-- Baseline schema - the tables as they existed before the security rework.
-- Reconstructed from the live schema so a fresh database (local dev / a new
-- environment) can be built from migrations alone. The later 20260809*ND
-- migrations lock this down (RLS, grants, write RPCs) on top of it.
-- ============================================================================

create table if not exists public.shops (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  address       text not null,
  latitude      double precision not null,
  longitude     double precision not null,
  image_url     text,
  archived      boolean not null default false,
  canonical_key text unique,
  apple_place_id text unique,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint unique_shop_name_address unique (name, address)
);

create table if not exists public.drinks (
  id   uuid primary key default gen_random_uuid(),
  name text not null
);

create table if not exists public.shop_drinks (
  id              uuid primary key default gen_random_uuid(),
  shop_id         uuid references public.shops (id),
  drink_id        uuid references public.drinks (id),
  price           numeric,
  cover_photo_url text,
  avg_rating      numeric,
  constraint unique_shop_drink_pair unique (shop_id, drink_id)
);

create table if not exists public.categories (
  id         integer generated by default as identity primary key,
  slug       text not null unique,
  label      text not null,
  sort_order integer
);

create table if not exists public.shop_drink_categories (
  shop_drink_id uuid not null references public.shop_drinks (id),
  category_id   integer not null references public.categories (id),
  primary key (shop_drink_id, category_id)
);

create table if not exists public.reviews (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references auth.users (id),
  shop_drink_id uuid not null references public.shop_drinks (id),
  rating        real not null,
  comment       text not null,
  media_urls    text[],
  created_at    timestamp not null default now()
);

-- Profile mirror (password column is dropped again by a later migration; kept
-- here for historical fidelity).
create table if not exists public.users (
  id         uuid primary key references auth.users (id),
  username   text unique,
  avatar_url text,
  password   text,
  created_at timestamptz default now()
);

-- Server-side cache for the Apple Maps proxy (maps edge function).
create table if not exists public.apple_maps_token_cache (
  key        text primary key,
  value      text not null,
  expires_at timestamptz not null
);
